In [2]:
import tensorflow as tf
import numpy as np

In [3]:
# normalize (mean around 0 std 1)
d = np.array([[15], [78], [12], [286]], dtype=float)

print(d)
print("Keras:")
print(tf.keras.utils.normalize(d, axis=0, order=2))

[[ 15.]
 [ 78.]
 [ 12.]
 [286.]]
Keras:
[[0.0504936 ]
 [0.26256674]
 [0.04039488]
 [0.9627447 ]]


In [4]:
# standardize (between 0 and 1)
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(0, 1))
scaler.fit(d)
print("Sklearn:")
scaler.transform(d)

Sklearn:


array([[0.01094891],
       [0.24087591],
       [0.        ],
       [1.        ]])

In [5]:
# categorical
tf.keras.utils.to_categorical(d, num_classes=287)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])